export { default as WavesStoryImg } from './waves-story.webp'
export { default as WavesSplashImg } from './waves-splash.webp'
export { default as WavesBackgroundImg } from './waves-background.webp'

export { default as WavesDeckNurtureCompleteImg } from './waves-deck-nurture-complete.webp'
export { default as WavesDeckNurtureImg } from './waves-deck-nurture.webp'
export { default as WavesDeckPlantsImg } from './waves-deck-plants.webp'
export { default as WavesOnboardSelectElementImg } from './waves-onboard-select-element.webp'
export { default as WavesOnboardSelectPlantImg } from './waves-onboard-select-plant.webp'
export { default as WavesOnboardGeneratedCreaturesImg } from './waves-onboard-generated-creatures.webp'
