export { default as GMArchitectureImg } from './gm-architecture.webp'
export { default as GMBackgroundImg } from './gm-background.webp'
export { default as GMDevelopmentImg } from './gm-development.webp'
export { default as GMDevelopment2Img } from './gm-development2.webp'
export { default as GMLearningsImg } from './gm-learnings.webp'
export { default as GMProblemImg } from './gm-problem.webp'

export { default as GMArchitecturePlaceholderImg } from './gm-architecture-ph.webp'
export { default as GMBackgroundPlaceholderImg } from './gm-background-ph.webp'
export { default as GMDevelopment2PlaceholderImg } from './gm-development2-ph.webp'
export { default as GMLearningsPlaceholderImg } from './gm-learnings-ph.webp'
export { default as GMProblemPlaceholderImg } from './gm-problem-ph.webp'
