export { default as GMArchitectureImg } from './gm-architecture.png'
export { default as GMBackgroundImg } from './gm-background.png'
export { default as GMDevelopmentImg } from './gm-development.png'
export { default as GMDevelopment2Img } from './gm-development2.png'
export { default as GMLearningsImg } from './gm-learnings.png'
export { default as GMProblemImg } from './gm-problem.png'

export { default as GMArchitecturePlaceholderImg } from './gm-architecture-ph.png'
export { default as GMBackgroundPlaceholderImg } from './gm-background-ph.png'
export { default as GMDevelopment2PlaceholderImg } from './gm-development2-ph.png'
export { default as GMLearningsPlaceholderImg } from './gm-learnings-ph.png'
export { default as GMProblemPlaceholderImg } from './gm-problem-ph.png'
