export { default as GMArchitectureImg } from './gm-architecture.png'
export { default as GMBackgroundImg } from './gm-background.png'
export { default as GMDevelopmentImg } from './gm-development.png'
export { default as GMDevelopment2Img } from './gm-development2.png'
export { default as GMLearningsImg } from './gm-learnings.png'
export { default as GMProblemImg } from './gm-problem.png'

export { default as gmBackgroundImgLarge } from './spr-background-large.jpg'
export { default as gmBackgroundImgPlaceholder } from './spr-background-placeholder.jpg'
export { default as gmBackgroundImg } from './spr-background.jpg'
