export { default as WefaStoryImg } from './wefa-story.webp'
export { default as WefaSplashImg } from './wefa-splash.webp'
export { default as WefaAppHomeImg } from './wefa-app-home.webp'
export { default as WefaAppWorldImg } from './wefa-app-world.webp'
export { default as WefaBackgroundImg } from './wefa-background.webp'

export { default as WefaFruitsVsVegetablesImg } from './wefa-fruits-vs-vegetables.webp'
// export { default as WefaFruitsVsVegetablesPlaceholderImg } from './wefa-fruits-vs-vegetables-ph.webp'
export { default as WefaSpicesHerbsVsFlowersImg } from './wefa-spices-herbs-vs-flowers.webp'
// export { default as WefaSpicesHerbsVsFlowersPlaceholderImg } from './wefa-spices-herbs-vs-flowers-ph.webp'
