export { default as WefaStoryImg } from './wefa-story.webp'
export { default as WefaSplashImg } from './wefa-splash.webp'
export { default as WefaBackgroundImg } from './wefa-background.webp'

export { default as WefaDeckNurtureCompleteImg } from './wefa-deck-nurture-complete.webp'
export { default as WefaDeckNurtureImg } from './wefa-deck-nurture.webp'
export { default as WefaDeckPlantsImg } from './wefa-deck-plants.webp'
export { default as WefaOnboardSelectElementImg } from './wefa-onboard-select-element.webp'
export { default as WefaOnboardSelectPlantImg } from './wefa-onboard-select-plant.webp'
export { default as WefaOnboardGeneratedCreaturesImg } from './wefa-onboard-generated-creatures.webp'
